class SaleModel {
  int? id; // optional, generated by DB
  String datetime; // ISO string, required
  double amount; // required
  int customerId; // optional, defaults to 0 (walk-in)
  int synced; // 0 = not synced, 1 = synced

  SaleModel({
    this.id,
    required this.datetime,
    required this.amount,
    this.customerId = 0,
    this.synced = 0,
  });

  Map<String, dynamic> toMap() {
    return {
      if (id != null) 'id': id,
      'datetime': datetime,
      'amount': amount,
      'customer_id': customerId,
      'synced': synced,
    };
  }

  factory SaleModel.fromMap(Map<String, dynamic> map) {
    return SaleModel(
      id: map['id'] as int?,
      datetime: map['datetime'] as String,
      amount: (map['amount'] as num?)?.toDouble() ?? 0.0,
      customerId: map['customer_id'] as int? ?? 0,
      synced: map['synced'] as int? ?? 0,
    );
  }

  SaleModel copyWith({
    int? id,
    String? datetime,
    double? amount,
    int? customerId,
    int? synced,
  }) {
    return SaleModel(
      id: id ?? this.id,
      datetime: datetime ?? this.datetime,
      amount: amount ?? this.amount,
      customerId: customerId ?? this.customerId,
      synced: synced ?? this.synced,
    );
  }

  @override
  String toString() {
    return 'Sale(id: $id, datetime: $datetime, amount: $amount, customerId: $customerId, synced: $synced)';
  }
}
